--ALL QUERIES USED IN APP

CREATE TABLE USERS(

	ID INTEGER IDENTITY PRIMARY KEY,
	USERNAME VARCHAR(100),
	PASSWORD VARCHAR(60),
	EMAIL NVARCHAR(255),
	DOB DATE,
	PHONE_NO VARCHAR(22),
	AVATAR VARBINARY(MAX),
	DESCR VARCHAR(MAX),
	FOLLOWING_NO INT,
	FOLLOWERS_NO INT

)

SELECT * FROM USERS
WHERE USERNAME = 'amanuel2'
AND   PASSWORD = 'passwd';

DELETE FROM USERS
WHERE ID = 3;

DELETE FROM USERS
WHERE ID = 7;

INSERT INTO USERS VALUES ('abogale2@gmail.com', 'pass', '29/12/2000', '4438517007', 'Blah blah lbah...', 0, 0)

SELECT AVATAR
FROM USERS
WHERE USERNAME='amanuel2'

DROP TABLE USERS



DECLARE @pswd VARCHAR(60) = 'passwd'
DECLARE @enc VARBINARY(MAX) = CAST(@pswd AS VARBINARY(max))
PRINT CAST(@enc AS VARCHAR(60))

CREATE TABLE SERVICES(
	ID INTEGER IDENTITY PRIMARY KEY,
	TITLE VARCHAR(100),
	DESCR VARCHAR(MAX),
	ASSIGNER INTEGER, --ID
	WORKER	 INTEGER, -- ID
	TAGS VARCHAR(100),
	STATE_ID INTEGER
)

CREATE TABLE SERVICES_STATE_ID(
	ID INTEGER IDENTITY PRIMARY KEY,
	STATE_NAME VARCHAR(30)
)

INSERT INTO SERVICES_STATE_ID VALUES('Not Assigned')
INSERT INTO SERVICES_STATE_ID VALUES('Pending')
INSERT INTO SERVICES_STATE_ID VALUES('Finished')

SELECT *
FROM SERVICES_STATE_ID

INSERT INTO SERVICES VALUES('Build an app', 'Help me build an app', 1, NULL, 'Coding,Education', 1)
INSERT INTO SERVICES VALUES('Make a beat', 'Give me a beat', 1, NULL, 'Music', 1)
INSERT INTO SERVICES VALUES('Maw my lawn', 'Help me maw my lawn', 1, NULL, 'Outdoor', 1)

SELECT *
FROM SERVICES

SELECT STATE_NAME
FROM SERVICES
INNER JOIN SERVICES_STATE_ID
ON SERVICES.STATE_ID=SERVICES_STATE_ID.ID


