-- Base Layout for Services
CREATE TABLE SERVICES(
	ID INTEGER IDENTITY PRIMARY KEY,
	TITLE VARCHAR(100),
	DESCR VARCHAR(MAX),
	ASSIGNER INTEGER, --ID
	WORKER	 INTEGER, -- ID
	TAGS VARCHAR(100),
	STATE_ID INTEGER
)


--Lookup table for the service state
CREATE TABLE SERVICES_STATE_ID(
	ID INTEGER IDENTITY PRIMARY KEY,
	STATE_NAME VARCHAR(30)
)

--default lookup values
INSERT INTO SERVICES_STATE_ID VALUES('Not Assigned')
INSERT INTO SERVICES_STATE_ID VALUES('Pending')
INSERT INTO SERVICES_STATE_ID VALUES('Finished')