CREATE TABLE USERS(

	ID INTEGER IDENTITY PRIMARY KEY,
	USERNAME VARCHAR(100),
	PASSWORD VARCHAR(60),
	EMAIL NVARCHAR(255),
	DOB DATE,
	PHONE_NO VARCHAR(22),
	AVATAR VARBINARY(MAX),
	DESCR VARCHAR(MAX),
	FOLLOWING_NO INT,
	FOLLOWERS_NO INT

)